// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamsPersistanceCenter.Models.Contexts;

namespace TeamsPersistanceCenter.Models.Migrations
{
    [DbContext(typeof(TeamsPersistanceContext))]
    [Migration("20220726054654_editadminvalue")]
    partial class editadminvalue
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeamsPersistanceCenter.Models.Administrator", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("IsValid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("Id");

                    b.ToTable("Administrator");
                });

            modelBuilder.Entity("TeamsPersistanceCenter.Models.AssignNumber", b =>
                {
                    b.Property<string>("Num")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte>("isUsed")
                        .HasColumnType("tinyint");

                    b.HasKey("Num");

                    b.ToTable("AssignNumber");
                });

            modelBuilder.Entity("TeamsPersistanceCenter.Models.User", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Num")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
